debug: true

server:
  host: 127.0.0.1
  port: 8889

  readTimeout: 60
  writeTimeout: 60
  idleTimeout: 180

sentry:
  dsn: ""
  ## zapcore.Level
  reportLogLevel: 2


databases:
  - id: "apigateway"
    host: "9.134.75.166"
    port: 3306
    user: "root"
    password: "mypass"
    name: "bk_apigateway"
    maxOpenConns: 200
    maxIdleConns: 50
    connMaxLifetimeSecond: 600

logger:
  default:
    level: debug
    writer: os
    buffered: false
    settings: {name: stdout}
  api:
    level: debug
    writer: os
    buffered: true
    settings: {name: stdout, size: 100, backups: 10, age: 7, path: ./}
      # 敏感日志配置
    desensitization:
      ## 日志脱敏开关配置
      enabled: false
      ## 日志脱敏规则配置: key -- 日志打印 field 的 key，jsonPath -- 日志 value 需要脱敏的 json path 路径
      fields:
        - key: body
          jsonPath:
            - "bk_app_secret"
        - key: response_body
          jsonPath:
            - "bk_app_secret"
            - "data.#.bk_app_secret"

## config for trace
tracing:
  enable: true
  endpoint: "127.0.0.1:4318"
  ## report type: grpc/http
  type: "http"
  ## support: "always_on"/"always_off"/"trace_id_ratio"/"parentbased_always_on",if not config,default: "trace_id_ratio"
  sampler: "trace_id_ratio"
  samplerRatio: 0.001
  token: "blueking"
  serviceName: "apigateway-mcp-proxy"
  instrument:
    ginAPI: true
    dbAPI: true