# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_server', '0012_mcpserver_oauth2_public_client_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcpserver',
            name='raw_response',
            field=models.BooleanField(
                default=False,
                help_text='是否返回原始响应，开启后工具调用将直接返回 API 原始响应，不再包装 request_id/status_code 等字段',
            ),
        ),
    ]
